Block test/unit/cbus_hang test
At the commit 63d75e92f6d5b8417ae8a973ab2ce44e574f46fc in
Tarantool the new test test/unit/cbus_hang.c created. It
breaks the Tarantool build with error:
 /usr/src/tarantool/test/unit/cbus_hang.c: In function 'main_f':
 /usr/src/tarantool/test/unit/cbus_hang.c:133:27: error: \
'pthread_mutex_t {aka struct <anonymous>}' has no member named '__data'
   while(hang_endpoint.mutex.__data.__lock < 2) {
                            ^
Found that mutex on Alpine 3.5 has no member named '__data',
to avoid of this issue the fixing commit cherry picked:

commit d7fa6d34ab4e0956fe8a80966ba628e0e3f81067
Author: Leonid Vasiliev <lvasiliev@tarantool.org>
Date:   Tue Apr 21 19:16:17 2020 +0300

    build: fix compilation on Alpine 3.5

    The cbus hang test uses glibc pthread mutex implementation details.
    The reason why mutex implementation details is used:
    "For the bug reproducing the canceled thread must be canceled
    during processing cpipe_flush_cb. We need to synchronize
    the main thread and the canceled worker thread for that.
    So, thread synchronization has been realized by means of
    endpoint's mutex internal field(__data.__lock)."
    Therefore, it should not compile in case of using another library.