Add unzip tool to rocks installations
Found issue:

  tarantoolctl rocks install ldoc --server=http://rocks.moonscript.org
  Warning: Failed searching manifest: Failed extracting manifest file:
    'unzip -n' program not found. Make sure unzip is installed and is
    available in your PATH (or you may want to edit the 'variables.UNZIP'
    value in file '/usr/local/etc/tarantool/rocks/config-5.1.lua')
  ldoc not found for Lua 5.1.
  ...
  Error: No results matching query were found for Lua 5.1.

To fix it the unzip package tool was added to be installed before rocks
installations.